import { Entity } from "@/types";

export const entities: Entity[] = [
  {
    id: "ent_01",
    name: "Meridian Capital Partners",
    legalName: "Meridian Capital Partners LLC",
    type: "llc",
    status: "active",
    riskLevel: "low",
    riskScore: 18,
    country: "US",
    registrationNumber: "LLC-2019-48291",
    taxId: "82-4719283",
    incorporationDate: "2019-03-15",
    industry: "Financial Services",
    website: "https://meridiancapital.com",
    address: {
      line1: "200 Park Avenue",
      line2: "Suite 1500",
      city: "New York",
      state: "NY",
      postalCode: "10166",
      country: "US",
    },
    contacts: [
      { name: "Sarah Chen", role: "CEO", email: "s.chen@meridiancapital.com", phone: "+1-212-555-0101" },
      { name: "David Park", role: "Compliance Officer", email: "d.park@meridiancapital.com" },
    ],
    beneficialOwners: [
      { id: "bo_01", individualId: "ind_01", name: "Sarah Chen", ownershipPercentage: 45, controlType: "direct", nationality: "US", verified: true },
      { id: "bo_02", individualId: "ind_02", name: "James Wright", ownershipPercentage: 35, controlType: "direct", nationality: "US", verified: true },
      { id: "bo_03", name: "Linda Zhao", ownershipPercentage: 20, controlType: "indirect", nationality: "CN", verified: false },
    ],
    documents: [
      { id: "doc_e01", type: "certificate_of_incorporation", name: "Certificate of Formation", status: "verified", uploadedAt: "2024-01-10T09:00:00Z" },
      { id: "doc_e02", type: "articles_of_association", name: "Operating Agreement", status: "verified", uploadedAt: "2024-01-10T09:05:00Z" },
      { id: "doc_e03", type: "financial_statement", name: "2024 Audited Financials", status: "pending", uploadedAt: "2025-02-15T14:30:00Z" },
    ],
    tags: ["financial-services", "us-based", "tier-1"],
    notes: "Long-standing client with clean compliance history.",
    assignedTo: "analyst_01",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2025-11-20T16:45:00Z",
  },
  {
    id: "ent_02",
    name: "Nordic Timber Group",
    legalName: "Nordic Timber Group AS",
    type: "corporation",
    status: "active",
    riskLevel: "medium",
    riskScore: 42,
    country: "NO",
    registrationNumber: "NO-923456789",
    taxId: "923456789MVA",
    incorporationDate: "2012-06-22",
    industry: "Forestry & Logging",
    website: "https://nordictimber.no",
    address: {
      line1: "Storgata 12",
      city: "Oslo",
      postalCode: "0155",
      country: "NO",
    },
    contacts: [
      { name: "Erik Johansson", role: "Managing Director", email: "erik@nordictimber.no", phone: "+47-22-555-100" },
    ],
    beneficialOwners: [
      { id: "bo_04", name: "Erik Johansson", ownershipPercentage: 60, controlType: "direct", nationality: "NO", verified: true },
      { id: "bo_05", name: "Olaf Svensson", ownershipPercentage: 40, controlType: "direct", nationality: "SE", verified: true },
    ],
    documents: [
      { id: "doc_e04", type: "certificate_of_incorporation", name: "Firmaattest", status: "verified", uploadedAt: "2024-03-05T10:00:00Z" },
      { id: "doc_e05", type: "tax_return", name: "2024 Skattemelding", status: "verified", uploadedAt: "2025-04-20T11:00:00Z" },
    ],
    tags: ["forestry", "nordic", "export"],
    assignedTo: "analyst_02",
    createdAt: "2024-03-05T08:00:00Z",
    updatedAt: "2025-10-15T09:30:00Z",
  },
  {
    id: "ent_03",
    name: "Al-Rashid Trading Co.",
    legalName: "Al-Rashid Trading Company WLL",
    type: "partnership",
    status: "active",
    riskLevel: "high",
    riskScore: 71,
    country: "AE",
    registrationNumber: "DED-847291",
    incorporationDate: "2008-11-03",
    industry: "Import/Export",
    website: "https://alrashidtrading.ae",
    address: {
      line1: "Dubai World Trade Centre",
      line2: "Tower B, Floor 18",
      city: "Dubai",
      postalCode: "9292",
      country: "AE",
    },
    contacts: [
      { name: "Mohammed Al-Rashid", role: "Chairman", email: "m.alrashid@alrashidtrading.ae", phone: "+971-4-555-8800" },
      { name: "Fatima Khalil", role: "CFO", email: "f.khalil@alrashidtrading.ae" },
    ],
    beneficialOwners: [
      { id: "bo_06", individualId: "ind_05", name: "Mohammed Al-Rashid", ownershipPercentage: 70, controlType: "direct", nationality: "AE", verified: true },
      { id: "bo_07", name: "Hassan Al-Rashid", ownershipPercentage: 30, controlType: "direct", nationality: "AE", verified: false },
    ],
    documents: [
      { id: "doc_e06", type: "certificate_of_incorporation", name: "Trade License", status: "verified", uploadedAt: "2024-05-20T08:00:00Z" },
      { id: "doc_e07", type: "financial_statement", name: "2024 Financial Report", status: "pending", uploadedAt: "2025-03-01T12:00:00Z" },
    ],
    tags: ["trading", "middle-east", "high-risk-jurisdiction"],
    notes: "Operates in multiple jurisdictions. Enhanced due diligence required.",
    assignedTo: "analyst_03",
    createdAt: "2024-05-20T07:00:00Z",
    updatedAt: "2025-12-01T14:00:00Z",
  },
  {
    id: "ent_04",
    name: "Greenleaf Foundation",
    legalName: "Greenleaf Charitable Foundation",
    type: "non_profit",
    status: "active",
    riskLevel: "low",
    riskScore: 12,
    country: "GB",
    registrationNumber: "CH-1182934",
    incorporationDate: "2015-09-01",
    industry: "Non-Profit / Charity",
    website: "https://greenleaffoundation.org.uk",
    address: {
      line1: "45 Kensington High Street",
      city: "London",
      postalCode: "W8 5ED",
      country: "GB",
    },
    contacts: [
      { name: "Emma Thompson", role: "Executive Director", email: "e.thompson@greenleaf.org.uk", phone: "+44-20-7555-3200" },
    ],
    beneficialOwners: [],
    documents: [
      { id: "doc_e08", type: "certificate_of_incorporation", name: "Charity Commission Registration", status: "verified", uploadedAt: "2024-02-14T09:00:00Z" },
    ],
    tags: ["charity", "uk", "low-risk"],
    createdAt: "2024-02-14T08:00:00Z",
    updatedAt: "2025-08-10T11:15:00Z",
  },
  {
    id: "ent_05",
    name: "SilkRoad Logistics",
    legalName: "SilkRoad Logistics Pte Ltd",
    type: "corporation",
    status: "suspended",
    riskLevel: "critical",
    riskScore: 89,
    country: "SG",
    registrationNumber: "SG-201934567K",
    taxId: "T19SG34567K",
    incorporationDate: "2019-07-15",
    industry: "Logistics & Freight",
    address: {
      line1: "1 Raffles Place",
      line2: "#44-02 One Raffles Place",
      city: "Singapore",
      postalCode: "048616",
      country: "SG",
    },
    contacts: [
      { name: "Wei Lin", role: "Director", email: "w.lin@silkroadlogistics.sg" },
    ],
    beneficialOwners: [
      { id: "bo_08", name: "Wei Lin", ownershipPercentage: 40, controlType: "direct", nationality: "SG", verified: true },
      { id: "bo_09", name: "Unknown Nominee Structure", ownershipPercentage: 60, controlType: "indirect", nationality: "VG", verified: false },
    ],
    documents: [
      { id: "doc_e09", type: "certificate_of_incorporation", name: "ACRA Registration", status: "verified", uploadedAt: "2024-06-01T10:00:00Z" },
      { id: "doc_e10", type: "financial_statement", name: "2023 Financials", status: "rejected", uploadedAt: "2024-12-15T09:00:00Z" },
    ],
    tags: ["logistics", "asia", "nominee-structure", "suspended"],
    notes: "Suspended pending UBO verification. Complex nominee structure through BVI.",
    assignedTo: "analyst_03",
    createdAt: "2024-06-01T07:00:00Z",
    updatedAt: "2026-01-05T10:30:00Z",
  },
  {
    id: "ent_06",
    name: "Bavaria Pharma GmbH",
    legalName: "Bavaria Pharmaceuticals Gesellschaft mit beschränkter Haftung",
    type: "corporation",
    status: "active",
    riskLevel: "low",
    riskScore: 15,
    country: "DE",
    registrationNumber: "HRB-287491",
    taxId: "DE314159265",
    incorporationDate: "2005-04-12",
    industry: "Pharmaceuticals",
    website: "https://bavariapharma.de",
    address: {
      line1: "Maximilianstraße 35",
      city: "Munich",
      state: "Bavaria",
      postalCode: "80539",
      country: "DE",
    },
    contacts: [
      { name: "Dr. Klaus Weber", role: "CEO", email: "k.weber@bavariapharma.de", phone: "+49-89-555-4400" },
      { name: "Anna Müller", role: "Head of Compliance", email: "a.mueller@bavariapharma.de" },
    ],
    beneficialOwners: [
      { id: "bo_10", name: "Dr. Klaus Weber", ownershipPercentage: 51, controlType: "direct", nationality: "DE", verified: true },
      { id: "bo_11", name: "Maximilian Bauer", ownershipPercentage: 49, controlType: "direct", nationality: "DE", verified: true },
    ],
    documents: [
      { id: "doc_e11", type: "certificate_of_incorporation", name: "Handelsregisterauszug", status: "verified", uploadedAt: "2024-04-01T08:00:00Z" },
      { id: "doc_e12", type: "financial_statement", name: "2024 Jahresabschluss", status: "verified", uploadedAt: "2025-06-15T10:00:00Z" },
    ],
    tags: ["pharma", "germany", "eu"],
    createdAt: "2024-04-01T07:00:00Z",
    updatedAt: "2025-09-20T13:00:00Z",
  },
];
