import { Individual } from "@/types";

export const individuals: Individual[] = [
  {
    id: "ind_01",
    firstName: "Sarah",
    lastName: "Chen",
    email: "s.chen@meridiancapital.com",
    phone: "+1-212-555-0101",
    dateOfBirth: "1978-04-23",
    nationality: "US",
    countryOfResidence: "US",
    status: "active",
    kycStatus: "verified",
    riskLevel: "low",
    riskScore: 12,
    address: {
      line1: "88 Central Park West",
      line2: "Apt 14A",
      city: "New York",
      state: "NY",
      postalCode: "10023",
      country: "US",
    },
    documents: [
      { id: "doc_i01", type: "passport", name: "US Passport", status: "verified", uploadedAt: "2024-01-12T10:00:00Z", expiresAt: "2032-01-12T00:00:00Z" },
      { id: "doc_i02", type: "utility_bill", name: "ConEd Statement", status: "verified", uploadedAt: "2024-01-12T10:05:00Z" },
    ],
    pepStatus: false,
    sanctionsHit: false,
    adverseMedia: false,
    sourceOfFunds: "Employment & Investments",
    occupation: "Chief Executive Officer",
    employer: "Meridian Capital Partners LLC",
    entityIds: ["ent_01"],
    tags: ["ubo", "tier-1"],
    assignedTo: "analyst_01",
    lastScreeningDate: "2025-10-01T00:00:00Z",
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2025-10-01T09:00:00Z",
  },
  {
    id: "ind_02",
    firstName: "James",
    lastName: "Wright",
    email: "j.wright@meridiancapital.com",
    phone: "+1-212-555-0202",
    dateOfBirth: "1982-11-07",
    nationality: "US",
    countryOfResidence: "US",
    status: "active",
    kycStatus: "verified",
    riskLevel: "low",
    riskScore: 14,
    address: {
      line1: "425 East 58th Street",
      city: "New York",
      state: "NY",
      postalCode: "10022",
      country: "US",
    },
    documents: [
      { id: "doc_i03", type: "drivers_license", name: "NY Drivers License", status: "verified", uploadedAt: "2024-01-15T09:00:00Z", expiresAt: "2029-11-07T00:00:00Z" },
      { id: "doc_i04", type: "bank_statement", name: "JPMorgan Statement", status: "verified", uploadedAt: "2024-01-15T09:10:00Z" },
    ],
    pepStatus: false,
    sanctionsHit: false,
    adverseMedia: false,
    sourceOfFunds: "Employment",
    occupation: "Managing Partner",
    employer: "Meridian Capital Partners LLC",
    entityIds: ["ent_01"],
    tags: ["ubo"],
    assignedTo: "analyst_01",
    lastScreeningDate: "2025-10-01T00:00:00Z",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2025-10-01T09:00:00Z",
  },
  {
    id: "ind_03",
    firstName: "Elena",
    lastName: "Petrov",
    middleName: "Ivanovna",
    email: "elena.petrov@mail.ru",
    phone: "+7-495-555-3300",
    dateOfBirth: "1990-02-14",
    nationality: "RU",
    countryOfResidence: "GB",
    status: "active",
    kycStatus: "in_progress",
    riskLevel: "high",
    riskScore: 68,
    address: {
      line1: "12 Belgravia Square",
      city: "London",
      postalCode: "SW1X 8PH",
      country: "GB",
    },
    documents: [
      { id: "doc_i05", type: "passport", name: "Russian Passport", status: "verified", uploadedAt: "2024-08-20T11:00:00Z", expiresAt: "2029-08-20T00:00:00Z" },
      { id: "doc_i06", type: "proof_of_address", name: "Council Tax Bill", status: "pending", uploadedAt: "2025-01-10T14:00:00Z" },
    ],
    pepStatus: true,
    sanctionsHit: false,
    adverseMedia: true,
    sourceOfFunds: "Family Wealth & Business",
    occupation: "Investor",
    entityIds: [],
    tags: ["pep", "adverse-media", "enhanced-dd"],
    notes: "PEP: Father is former deputy minister. Adverse media: Mentioned in investigative article (no direct allegations).",
    assignedTo: "analyst_03",
    lastScreeningDate: "2025-12-15T00:00:00Z",
    createdAt: "2024-08-20T08:00:00Z",
    updatedAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "ind_04",
    firstName: "Aisha",
    lastName: "Okafor",
    email: "a.okafor@greenleaf.org.uk",
    phone: "+44-20-7555-3205",
    dateOfBirth: "1985-07-30",
    nationality: "NG",
    countryOfResidence: "GB",
    status: "active",
    kycStatus: "verified",
    riskLevel: "low",
    riskScore: 20,
    address: {
      line1: "33 Camden Road",
      city: "London",
      postalCode: "NW1 9LR",
      country: "GB",
    },
    documents: [
      { id: "doc_i07", type: "passport", name: "Nigerian Passport", status: "verified", uploadedAt: "2024-02-20T10:00:00Z", expiresAt: "2030-02-20T00:00:00Z" },
      { id: "doc_i08", type: "national_id", name: "UK BRP Card", status: "verified", uploadedAt: "2024-02-20T10:10:00Z", expiresAt: "2028-07-30T00:00:00Z" },
    ],
    pepStatus: false,
    sanctionsHit: false,
    adverseMedia: false,
    sourceOfFunds: "Employment",
    occupation: "Program Director",
    employer: "Greenleaf Charitable Foundation",
    entityIds: ["ent_04"],
    tags: ["charity-staff"],
    assignedTo: "analyst_02",
    lastScreeningDate: "2025-08-01T00:00:00Z",
    createdAt: "2024-02-20T08:00:00Z",
    updatedAt: "2025-08-01T09:00:00Z",
  },
  {
    id: "ind_05",
    firstName: "Mohammed",
    lastName: "Al-Rashid",
    email: "m.alrashid@alrashidtrading.ae",
    phone: "+971-4-555-8800",
    dateOfBirth: "1970-12-01",
    nationality: "AE",
    countryOfResidence: "AE",
    status: "active",
    kycStatus: "verified",
    riskLevel: "high",
    riskScore: 65,
    address: {
      line1: "Villa 42, Jumeirah Beach Road",
      city: "Dubai",
      postalCode: "12345",
      country: "AE",
    },
    documents: [
      { id: "doc_i09", type: "passport", name: "UAE Passport", status: "verified", uploadedAt: "2024-05-22T09:00:00Z", expiresAt: "2031-12-01T00:00:00Z" },
      { id: "doc_i10", type: "national_id", name: "Emirates ID", status: "verified", uploadedAt: "2024-05-22T09:10:00Z", expiresAt: "2028-12-01T00:00:00Z" },
    ],
    pepStatus: true,
    sanctionsHit: false,
    adverseMedia: false,
    sourceOfFunds: "Business & Inheritance",
    occupation: "Chairman",
    employer: "Al-Rashid Trading Company WLL",
    entityIds: ["ent_03"],
    tags: ["pep", "ubo", "high-risk-jurisdiction"],
    notes: "PEP: Member of Dubai Chamber of Commerce advisory board.",
    assignedTo: "analyst_03",
    lastScreeningDate: "2025-11-01T00:00:00Z",
    createdAt: "2024-05-22T08:00:00Z",
    updatedAt: "2025-11-01T10:00:00Z",
  },
  {
    id: "ind_06",
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "y.tanaka@example.jp",
    dateOfBirth: "1995-03-18",
    nationality: "JP",
    countryOfResidence: "JP",
    status: "active",
    kycStatus: "not_started",
    riskLevel: "low",
    riskScore: 8,
    address: {
      line1: "2-4-1 Marunouchi",
      city: "Tokyo",
      state: "Chiyoda-ku",
      postalCode: "100-0005",
      country: "JP",
    },
    documents: [],
    pepStatus: false,
    sanctionsHit: false,
    adverseMedia: false,
    occupation: "Software Engineer",
    entityIds: [],
    tags: ["new-applicant"],
    createdAt: "2026-02-20T08:00:00Z",
    updatedAt: "2026-02-20T08:00:00Z",
  },
  {
    id: "ind_07",
    firstName: "Carlos",
    lastName: "Mendes",
    middleName: "Silva",
    email: "carlos.mendes@example.br",
    phone: "+55-11-5555-7700",
    dateOfBirth: "1975-09-12",
    nationality: "BR",
    countryOfResidence: "BR",
    status: "active",
    kycStatus: "failed",
    riskLevel: "critical",
    riskScore: 85,
    address: {
      line1: "Av. Paulista, 1578",
      line2: "Conjunto 801",
      city: "São Paulo",
      state: "SP",
      postalCode: "01310-200",
      country: "BR",
    },
    documents: [
      { id: "doc_i11", type: "passport", name: "Brazilian Passport", status: "rejected", uploadedAt: "2025-06-10T10:00:00Z" },
      { id: "doc_i12", type: "national_id", name: "CPF/RG", status: "rejected", uploadedAt: "2025-06-10T10:15:00Z" },
    ],
    pepStatus: false,
    sanctionsHit: true,
    adverseMedia: true,
    sourceOfFunds: "Business",
    occupation: "Business Owner",
    entityIds: [],
    tags: ["sanctions-hit", "adverse-media", "blocked"],
    notes: "Sanctions match on OFAC SDN list. Adverse media: linked to money laundering investigation.",
    assignedTo: "analyst_03",
    lastScreeningDate: "2025-12-20T00:00:00Z",
    createdAt: "2025-06-10T08:00:00Z",
    updatedAt: "2025-12-20T15:00:00Z",
  },
  {
    id: "ind_08",
    firstName: "Ingrid",
    lastName: "Larsson",
    email: "ingrid.larsson@nordictimber.no",
    dateOfBirth: "1988-06-05",
    nationality: "SE",
    countryOfResidence: "NO",
    status: "active",
    kycStatus: "verified",
    riskLevel: "low",
    riskScore: 10,
    address: {
      line1: "Bygdøy allé 23",
      city: "Oslo",
      postalCode: "0262",
      country: "NO",
    },
    documents: [
      { id: "doc_i13", type: "passport", name: "Swedish Passport", status: "verified", uploadedAt: "2024-03-10T09:00:00Z", expiresAt: "2030-06-05T00:00:00Z" },
    ],
    pepStatus: false,
    sanctionsHit: false,
    adverseMedia: false,
    sourceOfFunds: "Employment",
    occupation: "Operations Manager",
    employer: "Nordic Timber Group AS",
    entityIds: ["ent_02"],
    tags: [],
    assignedTo: "analyst_02",
    lastScreeningDate: "2025-09-01T00:00:00Z",
    createdAt: "2024-03-10T08:00:00Z",
    updatedAt: "2025-09-01T09:00:00Z",
  },
];
