import { KycWorkflow } from "@/types";

export const kycWorkflows: KycWorkflow[] = [
  {
    id: "wf_01",
    name: "Standard Individual KYC",
    description: "Default KYC workflow for low-to-medium risk individuals. Includes document collection, identity verification, sanctions screening, PEP check, and automated risk assessment.",
    type: "kyc",
    status: "active",
    version: 3,
    isDefault: true,
    applicantType: "individual",
    steps: [
      { id: "ws_01_01", name: "Document Collection", type: "document_collection", order: 1, required: true, config: { requiredDocuments: ["passport_or_national_id", "proof_of_address"], maxUploadSizeMb: 10 }, timeoutHours: 72 },
      { id: "ws_01_02", name: "Identity Verification", type: "identity_verification", order: 2, required: true, config: { provider: "onfido", minMatchScore: 80, enableLiveness: false } },
      { id: "ws_01_03", name: "Sanctions Screening", type: "sanctions_screening", order: 3, required: true, config: { lists: ["OFAC SDN", "EU", "UN", "UK HMT"], fuzzyThreshold: 85 } },
      { id: "ws_01_04", name: "PEP Check", type: "pep_check", order: 4, required: true, config: { includeRelatives: true, depth: 2 } },
      { id: "ws_01_05", name: "Risk Assessment", type: "risk_assessment", order: 5, required: true, config: { scoringModelId: "rsm_01", autoApproveBelow: 25 } },
    ],
    conditions: [
      { id: "wc_01_01", field: "nationality", operator: "in", value: ["AF", "IR", "KP", "SY"], action: "escalate" },
      { id: "wc_01_02", field: "risk_score", operator: "greater_than", value: 60, action: "add_step", targetStepId: "manual_review" },
    ],
    tags: ["standard", "individual", "default"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2025-06-15T10:00:00Z",
  },
  {
    id: "wf_02",
    name: "Standard Business KYB",
    description: "Default KYB workflow for business entities. Covers document collection, registry verification, UBO identification, sanctions screening, and risk assessment.",
    type: "kyb",
    status: "active",
    version: 2,
    isDefault: true,
    applicantType: "entity",
    steps: [
      { id: "ws_02_01", name: "Document Collection", type: "document_collection", order: 1, required: true, config: { requiredDocuments: ["certificate_of_incorporation", "articles_of_association", "proof_of_address"], maxUploadSizeMb: 25 }, timeoutHours: 120 },
      { id: "ws_02_02", name: "Business Verification", type: "business_verification", order: 2, required: true, config: { provider: "bureau_van_dijk", verifyRegistry: true, verifyAddress: true } },
      { id: "ws_02_03", name: "UBO Verification", type: "ubo_verification", order: 3, required: true, config: { minOwnershipThreshold: 25, verifyAllAboveThreshold: true }, timeoutHours: 168 },
      { id: "ws_02_04", name: "Sanctions Screening", type: "sanctions_screening", order: 4, required: true, config: { lists: ["OFAC SDN", "EU", "UN", "UK HMT"], screenEntity: true, screenUBOs: true } },
      { id: "ws_02_05", name: "Risk Assessment", type: "risk_assessment", order: 5, required: true, config: { scoringModelId: "rsm_02", autoApproveBelow: 20 } },
    ],
    conditions: [
      { id: "wc_02_01", field: "country", operator: "in", value: ["AF", "IR", "KP", "SY"], action: "reject" },
      { id: "wc_02_02", field: "industry", operator: "in", value: ["gambling", "cryptocurrency", "arms"], action: "escalate" },
      { id: "wc_02_03", field: "ubo_unverified_count", operator: "greater_than", value: 0, action: "escalate" },
    ],
    tags: ["standard", "entity", "default"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2025-05-20T14:00:00Z",
  },
  {
    id: "wf_03",
    name: "Enhanced Individual KYC",
    description: "Enhanced due diligence workflow for high-risk individuals. Adds biometric verification, adverse media screening, and mandatory manual review.",
    type: "kyc",
    status: "active",
    version: 2,
    isDefault: false,
    applicantType: "individual",
    steps: [
      { id: "ws_03_01", name: "Document Collection", type: "document_collection", order: 1, required: true, config: { requiredDocuments: ["passport", "proof_of_address", "bank_statement"], maxUploadSizeMb: 10 }, timeoutHours: 72 },
      { id: "ws_03_02", name: "Identity Verification", type: "identity_verification", order: 2, required: true, config: { provider: "onfido", minMatchScore: 90, enableLiveness: true } },
      { id: "ws_03_03", name: "Biometric Check", type: "biometric_check", order: 3, required: true, config: { livenessRequired: true, minFaceMatchScore: 95 } },
      { id: "ws_03_04", name: "PEP Check", type: "pep_check", order: 4, required: true, config: { includeRelatives: true, depth: 3 } },
      { id: "ws_03_05", name: "Adverse Media Screening", type: "adverse_media", order: 5, required: true, config: { provider: "lexis_nexis", languages: ["en", "fr", "de", "es", "ar", "zh"], lookbackYears: 10 } },
      { id: "ws_03_06", name: "Manual Review", type: "manual_review", order: 6, required: true, config: { requireSeniorApproval: true, minReviewers: 2 }, timeoutHours: 48 },
    ],
    conditions: [
      { id: "wc_03_01", field: "sanctions_hit", operator: "equals", value: "true", action: "reject" },
    ],
    tags: ["enhanced", "individual", "high-risk"],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2025-08-10T11:00:00Z",
  },
  {
    id: "wf_04",
    name: "Enhanced Business KYB",
    description: "Enhanced KYB workflow for high-risk entities or complex corporate structures. Includes deep UBO verification and mandatory senior review.",
    type: "kyb",
    status: "active",
    version: 1,
    isDefault: false,
    applicantType: "entity",
    steps: [
      { id: "ws_04_01", name: "Document Collection", type: "document_collection", order: 1, required: true, config: { requiredDocuments: ["certificate_of_incorporation", "articles_of_association", "financial_statement", "proof_of_address"], maxUploadSizeMb: 50 }, timeoutHours: 168 },
      { id: "ws_04_02", name: "Business Verification", type: "business_verification", order: 2, required: true, config: { provider: "bureau_van_dijk", verifyRegistry: true, verifyAddress: true, verifyDirectors: true } },
      { id: "ws_04_03", name: "UBO Verification", type: "ubo_verification", order: 3, required: true, config: { minOwnershipThreshold: 10, verifyAllAboveThreshold: true, traceNominees: true }, timeoutHours: 336 },
      { id: "ws_04_04", name: "Sanctions Screening", type: "sanctions_screening", order: 4, required: true, config: { lists: ["OFAC SDN", "OFAC Consolidated", "EU", "UN", "UK HMT", "AU DFAT"], screenEntity: true, screenUBOs: true, screenDirectors: true } },
      { id: "ws_04_05", name: "Manual Review", type: "manual_review", order: 5, required: true, config: { requireSeniorApproval: true, minReviewers: 2, escalateToCompliance: true }, timeoutHours: 72 },
    ],
    conditions: [
      { id: "wc_04_01", field: "country", operator: "in", value: ["AF", "IR", "KP", "SY", "CU"], action: "reject" },
      { id: "wc_04_02", field: "nominee_structure", operator: "equals", value: "true", action: "escalate" },
    ],
    tags: ["enhanced", "entity", "high-risk"],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2025-07-01T09:00:00Z",
  },
  {
    id: "wf_05",
    name: "AML Transaction Review",
    description: "AML workflow triggered by suspicious transaction patterns. Includes transaction analysis, enhanced screening, and mandatory compliance review.",
    type: "aml",
    status: "active",
    version: 1,
    isDefault: true,
    applicantType: "both",
    steps: [
      { id: "ws_05_01", name: "Transaction Analysis", type: "risk_assessment", order: 1, required: true, config: { analyzePatterns: true, lookbackDays: 90 } },
      { id: "ws_05_02", name: "Sanctions Screening", type: "sanctions_screening", order: 2, required: true, config: { screenCounterparties: true, lists: ["OFAC SDN", "OFAC Consolidated", "EU", "UN", "UK HMT"] } },
      { id: "ws_05_03", name: "Manual Review", type: "manual_review", order: 3, required: true, config: { requireComplianceOfficer: true, generateSAR: true }, timeoutHours: 24 },
    ],
    conditions: [
      { id: "wc_05_01", field: "transaction_amount", operator: "greater_than", value: 50000, action: "escalate" },
    ],
    tags: ["aml", "transactions", "default"],
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2025-09-15T08:00:00Z",
  },
  {
    id: "wf_06",
    name: "Simplified KYC",
    description: "Lightweight KYC workflow for low-risk jurisdictions and small-value accounts. Minimal checks with automated approval.",
    type: "kyc",
    status: "inactive",
    version: 1,
    isDefault: false,
    applicantType: "individual",
    steps: [
      { id: "ws_06_01", name: "Document Collection", type: "document_collection", order: 1, required: true, config: { requiredDocuments: ["national_id_or_passport"], maxUploadSizeMb: 5 }, timeoutHours: 48 },
      { id: "ws_06_02", name: "Identity Verification", type: "identity_verification", order: 2, required: true, config: { provider: "onfido", minMatchScore: 70, enableLiveness: false } },
      { id: "ws_06_03", name: "Sanctions Screening", type: "sanctions_screening", order: 3, required: true, config: { lists: ["OFAC SDN", "EU", "UN"], fuzzyThreshold: 90 } },
    ],
    conditions: [],
    tags: ["simplified", "individual", "low-risk"],
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2025-01-10T12:00:00Z",
  },
];
