import { CustomProperty } from "@/types";

export const customProperties: CustomProperty[] = [
  {
    id: "prop_01",
    name: "annual_revenue",
    label: "Annual Revenue",
    description: "The entity's annual revenue in USD",
    type: "number",
    entityType: "entity",
    required: false,
    validation: { min: 0, max: 999999999999 },
    order: 1,
    status: "active",
    group: "Financial",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "prop_02",
    name: "employee_count",
    label: "Number of Employees",
    type: "number",
    entityType: "entity",
    required: false,
    validation: { min: 1, max: 10000000 },
    order: 2,
    status: "active",
    group: "Financial",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "prop_03",
    name: "account_purpose",
    label: "Purpose of Account",
    type: "select",
    entityType: "individual",
    required: true,
    options: [
      { label: "Personal Savings", value: "personal_savings" },
      { label: "Business Operations", value: "business_operations" },
      { label: "Investment", value: "investment" },
      { label: "Trading", value: "trading" },
      { label: "Remittance", value: "remittance" },
      { label: "Other", value: "other" },
    ],
    order: 1,
    status: "active",
    group: "Account",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "prop_04",
    name: "expected_monthly_volume",
    label: "Expected Monthly Transaction Volume",
    type: "select",
    entityType: "individual",
    required: true,
    options: [
      { label: "Under $1,000", value: "under_1k" },
      { label: "$1,000 - $10,000", value: "1k_10k" },
      { label: "$10,000 - $50,000", value: "10k_50k" },
      { label: "$50,000 - $100,000", value: "50k_100k" },
      { label: "Over $100,000", value: "over_100k" },
    ],
    order: 2,
    status: "active",
    group: "Account",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "prop_05",
    name: "operating_countries",
    label: "Countries of Operation",
    description: "All countries where the entity conducts business",
    type: "multi_select",
    entityType: "entity",
    required: true,
    options: [
      { label: "United States", value: "US" },
      { label: "United Kingdom", value: "GB" },
      { label: "Germany", value: "DE" },
      { label: "France", value: "FR" },
      { label: "Japan", value: "JP" },
      { label: "Singapore", value: "SG" },
      { label: "UAE", value: "AE" },
      { label: "Hong Kong", value: "HK" },
      { label: "Switzerland", value: "CH" },
      { label: "Other", value: "other" },
    ],
    order: 3,
    status: "active",
    group: "Operations",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "prop_06",
    name: "is_regulated",
    label: "Regulated Entity",
    description: "Whether the entity is subject to financial regulation",
    type: "boolean",
    entityType: "entity",
    required: true,
    defaultValue: false,
    order: 4,
    status: "active",
    group: "Compliance",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "prop_07",
    name: "regulator_name",
    label: "Regulator Name",
    description: "Primary financial regulator (if applicable)",
    type: "text",
    entityType: "entity",
    required: false,
    validation: { maxLength: 200 },
    order: 5,
    status: "active",
    group: "Compliance",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "prop_08",
    name: "secondary_nationality",
    label: "Secondary Nationality",
    description: "Dual citizenship or secondary nationality if applicable",
    type: "country",
    entityType: "individual",
    required: false,
    order: 3,
    status: "active",
    group: "Personal",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "prop_09",
    name: "website_url",
    label: "Company Website",
    type: "url",
    entityType: "entity",
    required: false,
    validation: { pattern: "^https?://.*", patternMessage: "Must be a valid URL starting with http:// or https://" },
    order: 6,
    status: "active",
    group: "General",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "prop_10",
    name: "internal_reference",
    label: "Internal Reference Code",
    description: "Legacy system reference identifier",
    type: "text",
    entityType: "application",
    required: false,
    validation: { minLength: 5, maxLength: 20, pattern: "^[A-Z0-9-]+$", patternMessage: "Only uppercase letters, numbers, and hyphens" },
    order: 1,
    status: "active",
    group: "System",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "prop_11",
    name: "transaction_category",
    label: "Transaction Category",
    type: "select",
    entityType: "transaction",
    required: false,
    options: [
      { label: "Payroll", value: "payroll" },
      { label: "Supplier Payment", value: "supplier_payment" },
      { label: "Client Invoice", value: "client_invoice" },
      { label: "Investment", value: "investment" },
      { label: "Loan Repayment", value: "loan_repayment" },
      { label: "Intercompany", value: "intercompany" },
      { label: "Other", value: "other" },
    ],
    order: 1,
    status: "active",
    group: "Classification",
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-04-01T00:00:00Z",
  },
  {
    id: "prop_12",
    name: "tax_residency",
    label: "Tax Residency Country",
    type: "country",
    entityType: "individual",
    required: false,
    order: 4,
    status: "inactive",
    group: "Tax",
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
];
