import { RiskAlert, MonitoringRule } from "@/types";

export const riskAlerts: RiskAlert[] = [
  {
    id: "alert_01",
    type: "pep_match",
    severity: "high",
    status: "investigating",
    entityType: "individual",
    entityId: "ind_03",
    entityName: "Elena Ivanovna Petrov",
    title: "PEP Family Member Match",
    description: "Elena Petrov identified as daughter of Andrei Petrov, former Deputy Minister of Finance (Russia). PEP database updated with new family connection.",
    source: "Dow Jones PEP Database",
    assignedTo: "analyst_03",
    createdAt: "2025-12-15T09:00:00Z",
    updatedAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "alert_02",
    type: "sanctions_hit",
    severity: "critical",
    status: "open",
    entityType: "individual",
    entityId: "ind_07",
    entityName: "Carlos Silva Mendes",
    title: "OFAC SDN Sanctions Match",
    description: "Carlos Mendes matches entry on OFAC Specially Designated Nationals list. Match confidence: 94%. Matched name: Carlos Mendes Silva. SDN List ID: 48291.",
    source: "OFAC SDN List",
    assignedTo: "analyst_03",
    createdAt: "2025-12-20T14:00:00Z",
    updatedAt: "2025-12-20T15:00:00Z",
  },
  {
    id: "alert_03",
    type: "adverse_media",
    severity: "medium",
    status: "resolved",
    entityType: "individual",
    entityId: "ind_03",
    entityName: "Elena Ivanovna Petrov",
    title: "Adverse Media - Investigative Article",
    description: "Subject mentioned in Financial Times investigative piece regarding Russian capital flows to London real estate. No direct allegations made against the individual.",
    source: "LexisNexis Media Monitoring",
    assignedTo: "analyst_03",
    resolvedAt: "2025-11-05T16:00:00Z",
    resolvedBy: "analyst_03",
    resolution: "Reviewed article. No direct allegations against client. Media mention noted in file. Continuing enhanced monitoring.",
    createdAt: "2025-10-28T08:00:00Z",
    updatedAt: "2025-11-05T16:00:00Z",
  },
  {
    id: "alert_04",
    type: "unusual_activity",
    severity: "high",
    status: "investigating",
    entityType: "entity",
    entityId: "ent_03",
    entityName: "Al-Rashid Trading Company WLL",
    title: "Unusual Transaction Pattern Detected",
    description: "3 wire transfers totaling $847,000 to previously unseen counterparties in 48-hour period. Amounts inconsistent with historical transaction patterns (avg monthly volume: $120,000).",
    source: "Transaction Monitoring System",
    assignedTo: "analyst_03",
    createdAt: "2025-11-14T15:30:00Z",
    updatedAt: "2025-11-15T08:00:00Z",
  },
  {
    id: "alert_05",
    type: "risk_score_change",
    severity: "medium",
    status: "resolved",
    entityType: "entity",
    entityId: "ent_02",
    entityName: "Nordic Timber Group AS",
    title: "Risk Score Increased",
    description: "Entity risk score increased from 28 to 42 following updated country risk assessment for Norway forestry sector and new adverse media regarding industry-wide environmental violations.",
    source: "Risk Scoring Engine",
    assignedTo: "analyst_02",
    resolvedAt: "2025-10-20T14:00:00Z",
    resolvedBy: "analyst_02",
    resolution: "Reviewed risk score increase. Industry-wide issue, not specific to client. Updated monitoring frequency from quarterly to monthly.",
    createdAt: "2025-10-15T09:00:00Z",
    updatedAt: "2025-10-20T14:00:00Z",
  },
  {
    id: "alert_06",
    type: "document_expired",
    severity: "low",
    status: "open",
    entityType: "individual",
    entityId: "ind_04",
    entityName: "Aisha Okafor",
    title: "Document Approaching Expiry",
    description: "UK BRP Card (doc_i08) expires on 2028-07-30. Renewal reminder scheduled per policy.",
    source: "Document Management System",
    createdAt: "2026-01-30T08:00:00Z",
    updatedAt: "2026-01-30T08:00:00Z",
  },
  {
    id: "alert_07",
    type: "screening_match",
    severity: "high",
    status: "dismissed",
    entityType: "entity",
    entityId: "ent_05",
    entityName: "SilkRoad Logistics Pte Ltd",
    title: "Potential Screening Match - Entity Name",
    description: "Entity name 'SilkRoad Logistics' partially matches 'Silk Road' entries in various databases. Investigation required to determine if connection exists.",
    source: "Automated Screening",
    assignedTo: "analyst_03",
    resolvedAt: "2024-06-05T12:00:00Z",
    resolvedBy: "analyst_03",
    resolution: "False positive. Name similarity only. No connection to illegal marketplace. Entity flagged for other reasons (UBO verification failure).",
    createdAt: "2024-06-01T10:30:00Z",
    updatedAt: "2024-06-05T12:00:00Z",
  },
];

export const monitoringRules: MonitoringRule[] = [
  {
    id: "mr_01",
    name: "Continuous Sanctions Monitoring",
    description: "Real-time screening of all active individuals and entities against updated sanctions lists.",
    status: "active",
    type: "continuous",
    conditions: [{ trigger: "sanctions_list_update", scope: "all_active" }],
    actions: ["alert", "suspend"],
    lastRunAt: "2026-02-23T06:00:00Z",
    nextRunAt: "2026-02-23T12:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-02-23T06:00:00Z",
  },
  {
    id: "mr_02",
    name: "PEP Database Refresh",
    description: "Weekly screening of all individuals flagged as PEP or PEP-adjacent against updated PEP databases.",
    status: "active",
    type: "periodic",
    frequency: "weekly",
    conditions: [{ trigger: "schedule", scope: "pep_flagged_individuals" }],
    actions: ["alert"],
    lastRunAt: "2026-02-17T02:00:00Z",
    nextRunAt: "2026-02-24T02:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-02-17T02:00:00Z",
  },
  {
    id: "mr_03",
    name: "Adverse Media Scan",
    description: "Daily automated scan for negative news coverage mentioning active individuals and entities.",
    status: "active",
    type: "periodic",
    frequency: "daily",
    conditions: [{ trigger: "schedule", scope: "all_active", minRiskLevel: "medium" }],
    actions: ["alert"],
    lastRunAt: "2026-02-23T03:00:00Z",
    nextRunAt: "2026-02-24T03:00:00Z",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2026-02-23T03:00:00Z",
  },
  {
    id: "mr_04",
    name: "Transaction Threshold Alert",
    description: "Flag any single transaction exceeding $10,000 or aggregate daily transactions exceeding $25,000.",
    status: "active",
    type: "continuous",
    conditions: [
      { trigger: "transaction_amount", operator: "greater_than", value: 10000 },
      { trigger: "daily_aggregate", operator: "greater_than", value: 25000 },
    ],
    actions: ["alert", "escalate"],
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2025-06-01T10:00:00Z",
  },
  {
    id: "mr_05",
    name: "Risk Score Drift Detection",
    description: "Monthly review of risk scores for all entities and individuals to detect significant changes.",
    status: "active",
    type: "periodic",
    frequency: "monthly",
    conditions: [{ trigger: "schedule", scope: "all_active", riskScoreChangThreshold: 10 }],
    actions: ["alert"],
    lastRunAt: "2026-02-01T04:00:00Z",
    nextRunAt: "2026-03-01T04:00:00Z",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2026-02-01T04:00:00Z",
  },
  {
    id: "mr_06",
    name: "Dormant Account Reactivation",
    description: "Alert when an account inactive for 90+ days shows new activity.",
    status: "active",
    type: "continuous",
    conditions: [{ trigger: "activity_after_dormancy", dormancyDays: 90 }],
    actions: ["alert"],
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2025-08-15T11:00:00Z",
  },
];
