import { ThemeConfig } from "@/types";

export const themes: ThemeConfig[] = [
  {
    id: "theme_01",
    name: "KYCGate Default",
    isActive: true,
    branding: {
      companyName: "KYCGate",
      tagline: "Compliance, Simplified.",
    },
    colors: {
      primary: "#2563EB",
      secondary: "#4F46E5",
      accent: "#06B6D4",
      background: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#0F172A",
      textSecondary: "#64748B",
      success: "#16A34A",
      warning: "#D97706",
      error: "#DC2626",
      info: "#2563EB",
    },
    typography: {
      fontFamily: "IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "IBM Plex Sans, system-ui, sans-serif",
      baseFontSize: "14px",
      headingWeight: "600",
    },
    components: {
      borderRadius: "8px",
      buttonStyle: "rounded",
      cardShadow: "sm",
      inputStyle: "outline",
    },
    updatedAt: "2025-06-01T10:00:00Z",
  },
  {
    id: "theme_02",
    name: "Dark Professional",
    isActive: false,
    branding: {
      companyName: "KYCGate",
      tagline: "Compliance, Simplified.",
    },
    colors: {
      primary: "#3B82F6",
      secondary: "#6366F1",
      accent: "#22D3EE",
      background: "#0F172A",
      surface: "#1E293B",
      text: "#F1F5F9",
      textSecondary: "#94A3B8",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#3B82F6",
    },
    typography: {
      fontFamily: "IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "IBM Plex Sans, system-ui, sans-serif",
      baseFontSize: "14px",
      headingWeight: "600",
    },
    components: {
      borderRadius: "8px",
      buttonStyle: "rounded",
      cardShadow: "md",
      inputStyle: "filled",
    },
    updatedAt: "2025-06-01T10:00:00Z",
  },
  {
    id: "theme_03",
    name: "Enterprise Minimal",
    isActive: false,
    branding: {
      companyName: "KYCGate",
      tagline: "Enterprise Compliance Platform",
    },
    colors: {
      primary: "#1D4ED8",
      secondary: "#374151",
      accent: "#0891B2",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      text: "#111827",
      textSecondary: "#6B7280",
      success: "#059669",
      warning: "#B45309",
      error: "#B91C1C",
      info: "#1D4ED8",
    },
    typography: {
      fontFamily: "IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "IBM Plex Sans, system-ui, sans-serif",
      baseFontSize: "13px",
      headingWeight: "700",
    },
    components: {
      borderRadius: "4px",
      buttonStyle: "square",
      cardShadow: "none",
      inputStyle: "outline",
    },
    updatedAt: "2025-08-15T14:00:00Z",
  },
  {
    id: "theme_04",
    name: "Golden Suisse",
    isActive: false,
    branding: {
      companyName: "Golden Suisse",
      tagline: "Preserving Wealth. Protecting Legacy. Ensuring Sovereignty.",
    },
    colors: {
      primary: "#B78B2E",
      secondary: "#1E2A31",
      accent: "#D4AF37",
      background: "#F7F4EE",
      surface: "#FFFFFF",
      text: "#1B1B1B",
      textSecondary: "#6F6A5D",
      success: "#2F7D55",
      warning: "#C08A1A",
      error: "#A63A2A",
      info: "#355C7D",
    },
    typography: {
      fontFamily: "Inter, IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "Playfair Display, Times New Roman, serif",
      baseFontSize: "14px",
      headingWeight: "700",
    },
    components: {
      borderRadius: "4px",
      buttonStyle: "square",
      cardShadow: "sm",
      inputStyle: "outline",
    },
    updatedAt: "2026-02-23T12:00:00Z",
  },
  {
    id: "theme_05",
    name: "InaBank",
    isActive: false,
    branding: {
      companyName: "InaBank",
      tagline: "Private onboarding with trusted compliance.",
    },
    colors: {
      primary: "#004555",
      secondary: "#396D7A",
      accent: "#86A1A9",
      background: "#F3F4F5",
      surface: "#F7F9FA",
      text: "#0F172A",
      textSecondary: "#396D7A",
      success: "#16A34A",
      warning: "#D97706",
      error: "#DC2626",
      info: "#2563EB",
    },
    typography: {
      fontFamily: "Proxima Nova, IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "GT Alpina, Times New Roman, serif",
      baseFontSize: "14px",
      headingWeight: "600",
    },
    components: {
      borderRadius: "4px",
      buttonStyle: "square",
      cardShadow: "sm",
      inputStyle: "outline",
    },
    updatedAt: "2026-02-23T12:30:00Z",
  },
];
