import { ThemeConfig } from "@/types";

export const themes: ThemeConfig[] = [
  {
    id: "theme_01",
    name: "KYCGate Default",
    isActive: true,
    branding: {
      companyName: "KYCGate",
      tagline: "Compliance, Simplified.",
    },
    colors: {
      primary: "#2563EB",
      secondary: "#4F46E5",
      accent: "#06B6D4",
      background: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#0F172A",
      textSecondary: "#64748B",
      success: "#16A34A",
      warning: "#D97706",
      error: "#DC2626",
      info: "#2563EB",
    },
    typography: {
      fontFamily: "IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "IBM Plex Sans, system-ui, sans-serif",
      baseFontSize: "14px",
      headingWeight: "600",
    },
    components: {
      borderRadius: "8px",
      buttonStyle: "rounded",
      cardShadow: "sm",
      inputStyle: "outline",
    },
    updatedAt: "2025-06-01T10:00:00Z",
  },
  {
    id: "theme_02",
    name: "Dark Professional",
    isActive: false,
    branding: {
      companyName: "KYCGate",
      tagline: "Compliance, Simplified.",
    },
    colors: {
      primary: "#3B82F6",
      secondary: "#6366F1",
      accent: "#22D3EE",
      background: "#0F172A",
      surface: "#1E293B",
      text: "#F1F5F9",
      textSecondary: "#94A3B8",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#3B82F6",
    },
    typography: {
      fontFamily: "IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "IBM Plex Sans, system-ui, sans-serif",
      baseFontSize: "14px",
      headingWeight: "600",
    },
    components: {
      borderRadius: "8px",
      buttonStyle: "rounded",
      cardShadow: "md",
      inputStyle: "filled",
    },
    updatedAt: "2025-06-01T10:00:00Z",
  },
  {
    id: "theme_03",
    name: "Enterprise Minimal",
    isActive: false,
    branding: {
      companyName: "KYCGate",
      tagline: "Enterprise Compliance Platform",
    },
    colors: {
      primary: "#1D4ED8",
      secondary: "#374151",
      accent: "#0891B2",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      text: "#111827",
      textSecondary: "#6B7280",
      success: "#059669",
      warning: "#B45309",
      error: "#B91C1C",
      info: "#1D4ED8",
    },
    typography: {
      fontFamily: "IBM Plex Sans, system-ui, sans-serif",
      headingFontFamily: "IBM Plex Sans, system-ui, sans-serif",
      baseFontSize: "13px",
      headingWeight: "700",
    },
    components: {
      borderRadius: "4px",
      buttonStyle: "square",
      cardShadow: "none",
      inputStyle: "outline",
    },
    updatedAt: "2025-08-15T14:00:00Z",
  },
];
