import { Transaction } from "@/types";

export const transactions: Transaction[] = [
  {
    id: "txn_01",
    type: "wire_transfer",
    status: "completed",
    amount: 250000,
    currency: "USD",
    direction: "outbound",
    senderName: "Meridian Capital Partners LLC",
    senderId: "ent_01",
    senderAccount: "****4821",
    senderCountry: "US",
    receiverName: "Nordic Timber Group AS",
    receiverId: "ent_02",
    receiverAccount: "****7392",
    receiverCountry: "NO",
    reference: "INV-2025-0847",
    riskFlags: [],
    riskScore: 8,
    screeningResult: "clear",
    narrative: "Investment payment per agreement dated 2025-10-01",
    createdAt: "2025-10-15T14:30:00Z",
    updatedAt: "2025-10-15T14:32:00Z",
  },
  {
    id: "txn_02",
    type: "wire_transfer",
    status: "flagged",
    amount: 347000,
    currency: "USD",
    direction: "outbound",
    senderName: "Al-Rashid Trading Company WLL",
    senderId: "ent_03",
    senderAccount: "****6614",
    senderCountry: "AE",
    receiverName: "Golden Star Commodities Ltd",
    receiverAccount: "****1198",
    receiverCountry: "HK",
    reference: "TRADE-24891",
    riskFlags: ["large_amount", "new_counterparty", "high_risk_corridor"],
    riskScore: 72,
    screeningResult: "pending",
    narrative: "Commodities trade settlement",
    createdAt: "2025-11-13T09:15:00Z",
    updatedAt: "2025-11-14T15:30:00Z",
  },
  {
    id: "txn_03",
    type: "wire_transfer",
    status: "flagged",
    amount: 289000,
    currency: "USD",
    direction: "outbound",
    senderName: "Al-Rashid Trading Company WLL",
    senderId: "ent_03",
    senderAccount: "****6614",
    senderCountry: "AE",
    receiverName: "Pacific Rim Trading Corp",
    receiverAccount: "****4420",
    receiverCountry: "SG",
    reference: "TRADE-24903",
    riskFlags: ["large_amount", "new_counterparty", "rapid_succession"],
    riskScore: 75,
    screeningResult: "pending",
    createdAt: "2025-11-14T11:00:00Z",
    updatedAt: "2025-11-14T15:30:00Z",
  },
  {
    id: "txn_04",
    type: "wire_transfer",
    status: "flagged",
    amount: 211000,
    currency: "USD",
    direction: "outbound",
    senderName: "Al-Rashid Trading Company WLL",
    senderId: "ent_03",
    senderAccount: "****6614",
    senderCountry: "AE",
    receiverName: "Eastwind Supply Chain Ltd",
    receiverAccount: "****8837",
    receiverCountry: "MY",
    reference: "TRADE-24915",
    riskFlags: ["large_amount", "new_counterparty", "rapid_succession"],
    riskScore: 70,
    screeningResult: "pending",
    createdAt: "2025-11-14T16:45:00Z",
    updatedAt: "2025-11-14T16:50:00Z",
  },
  {
    id: "txn_05",
    type: "ach",
    status: "completed",
    amount: 15000,
    currency: "USD",
    direction: "inbound",
    senderName: "Sarah Chen",
    senderId: "ind_01",
    senderAccount: "****9012",
    senderCountry: "US",
    receiverName: "Meridian Capital Partners LLC",
    receiverId: "ent_01",
    receiverAccount: "****4821",
    receiverCountry: "US",
    reference: "CAPITAL-CALL-2025-Q4",
    riskFlags: [],
    riskScore: 5,
    screeningResult: "clear",
    narrative: "Q4 2025 capital contribution",
    createdAt: "2025-10-01T10:00:00Z",
    updatedAt: "2025-10-01T10:02:00Z",
  },
  {
    id: "txn_06",
    type: "crypto",
    status: "blocked",
    amount: 89500,
    currency: "USDT",
    direction: "inbound",
    senderName: "Unknown Wallet",
    senderAccount: "0x7a2B...f9E4",
    senderCountry: "unknown",
    receiverName: "SilkRoad Logistics Pte Ltd",
    receiverId: "ent_05",
    receiverAccount: "****2211",
    receiverCountry: "SG",
    riskFlags: ["crypto", "unknown_sender", "suspended_account", "high_amount"],
    riskScore: 95,
    screeningResult: "hit",
    narrative: "Blocked: receiver account suspended. Sender wallet linked to mixer service.",
    createdAt: "2025-12-20T03:15:00Z",
    updatedAt: "2025-12-20T03:15:30Z",
  },
  {
    id: "txn_07",
    type: "wire_transfer",
    status: "completed",
    amount: 45000,
    currency: "EUR",
    direction: "outbound",
    senderName: "Bavaria Pharma GmbH",
    senderId: "ent_06",
    senderAccount: "****3301",
    senderCountry: "DE",
    receiverName: "Swiss Biotech Supplies AG",
    receiverAccount: "****5547",
    receiverCountry: "CH",
    reference: "PO-2025-12847",
    riskFlags: [],
    riskScore: 6,
    screeningResult: "clear",
    narrative: "Raw materials purchase order",
    createdAt: "2025-11-28T08:30:00Z",
    updatedAt: "2025-11-28T08:35:00Z",
  },
  {
    id: "txn_08",
    type: "card_payment",
    status: "completed",
    amount: 2750,
    currency: "GBP",
    direction: "outbound",
    senderName: "Greenleaf Foundation",
    senderId: "ent_04",
    senderAccount: "****8890",
    senderCountry: "GB",
    receiverName: "Conference & Events Ltd",
    receiverAccount: "****4412",
    receiverCountry: "GB",
    reference: "EVT-CHARITY-GALA-2025",
    riskFlags: [],
    riskScore: 3,
    screeningResult: "clear",
    narrative: "Annual charity gala venue booking",
    createdAt: "2025-11-05T15:20:00Z",
    updatedAt: "2025-11-05T15:20:30Z",
  },
  {
    id: "txn_09",
    type: "cash_deposit",
    status: "flagged",
    amount: 9900,
    currency: "USD",
    direction: "inbound",
    senderName: "Carlos Silva Mendes",
    senderId: "ind_07",
    senderCountry: "BR",
    receiverName: "Account Blocked",
    receiverCountry: "BR",
    riskFlags: ["cash", "just_below_threshold", "sanctions_match", "structuring_suspected"],
    riskScore: 92,
    screeningResult: "hit",
    narrative: "Cash deposit just below $10,000 reporting threshold. Account holder on sanctions list.",
    createdAt: "2025-06-08T14:00:00Z",
    updatedAt: "2025-06-10T09:00:00Z",
  },
  {
    id: "txn_10",
    type: "internal_transfer",
    status: "completed",
    amount: 500000,
    currency: "NOK",
    direction: "outbound",
    senderName: "Nordic Timber Group AS",
    senderId: "ent_02",
    senderAccount: "****7392",
    senderCountry: "NO",
    receiverName: "Nordic Timber Group - Operations",
    receiverAccount: "****7395",
    receiverCountry: "NO",
    reference: "INT-OPEX-2025-11",
    riskFlags: [],
    riskScore: 4,
    screeningResult: "clear",
    narrative: "Monthly operational budget transfer",
    createdAt: "2025-11-01T06:00:00Z",
    updatedAt: "2025-11-01T06:00:30Z",
  },
];
